version: "3"
services:
  app:
    image: node:18-slim
    volumes:
      - ./app:/usr/src/app
      - node_modules_volume:/usr/src/app/node_modules # node_modules/ は別ボリュームに退避
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true # Next.js アプリのホットリロード有効化
      - WATCHPACK_POLLING=true # Next.js アプリのホットリロード有効化

volumes:
  node_modules_volume:
